# Generated by Django 3.0.4 on 2020-04-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='bio',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
